### ISSUE TITLE
Problems with Report

### ISSUE THREAD

**Issue by ghost** [zoecastillo/microbiomeExplorer#3]
Hi!

Im trying to get the report and I get this error:

Listening on http://127.0.0.1:4554
-- Sending report to /var/folders/sy/4mzmjcq17txbv3vnznqk2v5c0000gn/T//RtmpHv8asR --
-- Removing /var/folders/sy/4mzmjcq17txbv3vnznqk2v5c0000gn/T//RtmpHv8asR/me_report.Rmd--
-- entering my report generator --
-- creating header --
-- setting toc ----- data processing ----- header created! --
-- build intro text --
-- merged code --
gen report try value: try-error

Im using R version 4.0.3 on macOs Catalina.

Any suggestion?

Best wishes!

A. Galiana

**Comment by zoecastillo** [comment]
I just updated my own system (same R version, also Catalina) and can still generate the reports.
So, it's not related to the R version or OS.

Could you please post your sessionInfo() after running runMicrobiomeExplorer()? 
It looks like the knitting or rendering step is not starting properly, but I don't know why. I had someone else report a similar issue from a windows environment. 

Thank you!

**Comment by ghost** [comment]
Hi Janina,

Thank you very much for your time and help. I don’t know if I understood you exactly but I tried (im very new with bioinformatics). I loaded microbiomeExplorer (library) on R and then I used "session_info(pkgs=NULL include_base=FALSE)” I got this:


 > session_info(pkgs = NULL, include_base = FALSE)
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       macOS High Sierra 10.13.6   
 system   x86_64, darwin17.0          
 ui       AQUA                        
 language (EN)                        
 collate  es_ES.UTF-8                 
 ctype    es_ES.UTF-8                 
 tz       Europe/Madrid               
 date     2021-01-15                  

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package            * version date       lib source                                         
 assertthat           0.2.1   2019-03-21 [1] CRAN (R 4.0.2)                                 
 Biobase            * 2.50.0  2020-10-27 [1] Bioconductor                                   
 BiocGenerics       * 0.36.0  2020-10-27 [1] Bioconductor                                   
 bitops               1.0-6   2013-08-17 [1] CRAN (R 4.0.2)                                 
 caTools              1.18.0  2020-01-17 [1] CRAN (R 4.0.2)                                 
 cli                  2.2.0   2020-11-20 [1] CRAN (R 4.0.2)                                 
 codetools            0.2-18  2020-11-04 [1] CRAN (R 4.0.2)                                 
 crayon               1.3.4   2017-09-16 [1] CRAN (R 4.0.2)                                 
 digest               0.6.27  2020-10-24 [1] CRAN (R 4.0.2)                                 
 fansi                0.4.1   2020-01-08 [1] CRAN (R 4.0.2)                                 
 fastmap              1.0.1   2019-10-08 [1] CRAN (R 4.0.2)                                 
 foreach              1.5.1   2020-10-15 [1] CRAN (R 4.0.2)                                 
 glmnet             * 4.0-2   2020-06-16 [1] CRAN (R 4.0.2)                                 
 glue                 1.4.2   2020-08-27 [1] CRAN (R 4.0.2)                                 
 gplots               3.1.1   2020-11-28 [1] CRAN (R 4.0.2)                                 
 gtools               3.8.2   2020-03-31 [1] CRAN (R 4.0.2)                                 
 htmltools            0.5.0   2020-06-16 [1] CRAN (R 4.0.2)                                 
 httpuv               1.5.4   2020-06-06 [1] CRAN (R 4.0.2)                                 
 iterators            1.0.13  2020-10-15 [1] CRAN (R 4.0.2)                                 
 KernSmooth           2.23-18 2020-10-29 [1] CRAN (R 4.0.2)                                 
 later                1.1.0.1 2020-06-05 [1] CRAN (R 4.0.2)                                 
 lattice              0.20-41 2020-04-02 [1] CRAN (R 4.0.3)                                 
 limma              * 3.46.0  2020-10-27 [1] Bioconductor                                   
 locfit               1.5-9.4 2020-03-25 [1] CRAN (R 4.0.2)                                 
 magrittr           * 2.0.1   2020-11-17 [1] CRAN (R 4.0.2)                                 
 Matrix             * 1.3-2   2021-01-06 [1] CRAN (R 4.0.2)                                 
 matrixStats          0.57.0  2020-09-25 [1] CRAN (R 4.0.2)                                 
 metagenomeSeq      * 1.32.0  2020-10-27 [1] Bioconductor                                   
 microbiomeExplorer * 1.0.4   2021-01-11 [1] Github (zoecastillo/microbiomeExplorer@e29de49)
 mime                 0.9     2020-02-04 [1] CRAN (R 4.0.2)                                 
 promises             1.1.1   2020-06-09 [1] CRAN (R 4.0.2)                                 
 R6                   2.5.0   2020-10-28 [1] CRAN (R 4.0.2)                                 
 RColorBrewer       * 1.1-2   2014-12-07 [1] CRAN (R 4.0.2)                                 
 Rcpp                 1.0.5   2020-07-06 [1] CRAN (R 4.0.2)                                 
 rlang                0.4.10  2020-12-30 [1] CRAN (R 4.0.2)                                 
 sessioninfo        * 1.1.1   2018-11-05 [1] CRAN (R 4.0.2)                                 
 shape                1.4.5   2020-09-13 [1] CRAN (R 4.0.2)                                 
 shiny              * 1.5.0   2020-06-23 [1] CRAN (R 4.0.2)                                 
 shinydashboard       0.7.1   2018-10-17 [1] CRAN (R 4.0.2)                                 
 survival             3.2-7   2020-09-28 [1] CRAN (R 4.0.3)                                 
 withr                2.3.0   2020-09-22 [1] CRAN (R 4.0.2)                                 
 Wrench               1.8.0   2020-10-28 [1] Bioconductor                                   
 xtable               1.8-4   2019-04-21 [1] CRAN (R 4.0.2)                                 

[1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

I tried also session info after running runMicrobiomeExplorer() but R doesn’t return any info, I don’t know if this is the info required (I hope yes). Reading the report I see I was wrong and my macOs version is High Sierra, I work in remote with a server which works with macOs catalina  (my bad) and before to install the packages on the server first I work local on my computer thats the reason of the mistake.

I hope it helps, once more thank you for your help.

Regards

Antonio

**Comment by zoecastillo** [comment]
Thank you!

Could you please try loading the knitr and rmarkdown packages explicitly before running runMicrobiomeExplorer()?
Those contain the functions we call to generate the reports, so it would be good to see which versions those are.

Another thing you could try is to look at the temp folder shown in the error reported after you attempt to generate the report while the application is still running. (above it is "/var/folders/sy/4mzmjcq17txbv3vnznqk2v5c0000gn/T//RtmpHv8asR", but this will be different every time you run the app). If that works, can you see any me_report.* files in there?

Best,

Janina

**Comment by ghost** [comment]
Hi Janina

I loaded knit (v 1.30) and rmarkdown (v 2.6) but same error:

-- Sending report to /var/folders/sr/2r58hx090yx8qzmvzv3zsk2m0000gp/T//Rtmpnz0ZsM --
-- Removing /var/folders/sr/2r58hx090yx8qzmvzv3zsk2m0000gp/T//Rtmpnz0ZsM/me_report.Rmd--
-- entering my report generator --
-- creating header --
-- setting toc ----- data processing ----- header created! --
-- build intro text --
-- merged code --
gen report try value: try-error

Any suggestion?

Best wishes

**Comment by ghost** [comment]
Hi Janina,

I have installed microbiomeExplorer in the server (macOS Catalina and R 4.0.3) and I get same error (I also tried to load first knitr and rmarkdown as you told me). Please find attached me_report if it helps.

Regards

**Comment by zoecastillo** [comment]
Thank you,

Those are the same versions my system uses. I will have to do some more testing to see if I can figure out what causes the problem. The only other thing I could think about right now would be pandoc, but if you can run knit markdown documents, it should be there (I think). But just in case, could you please check if pandoc is installed and findable in your system.

If it is, I will have to get back to you.

**Comment by ghost** [comment]
Hi Janina,

Now its working!! :) I had to solve some more errors, if it helps I did:

Install phantomjs on R —> webshot::install_phantomjs()

Then on terminal throw brew install basictex and throw pip install pandoc

Thank you for your help

Best wishes

A. Galiana

**Comment by zoecastillo** [comment]
Thank you very much for sharing this! 

I am very glad you were able to figure out the problem.
